# Generated by Django 3.0.4 on 2020-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('P', 'Pants'), ('SW', 'Sport wear'), ('OW', 'Outwear')], max_length=2),
        ),
    ]
