# Generated by Django 3.0.4 on 2020-05-07 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='active',
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='rates',
            field=models.IntegerField(default=1),
        ),
    ]
