# Generated by Django 3.0.4 on 2020-06-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200508_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
